### ISSUE TITLE
Can I run rfplasmid without running getdb.sh? (e.g. --help)

### ISSUE THREAD

**Issue by rpetit3** [aldertzomer/RFPlasmid#12]
At the moment `rfplasmid` and `rfplasmid --help` required the databases built by `getdb.sh` to exist.

For conda I think it would be useful to allow `rfplasmid` and `rfplasmid --help` to be executed without automatically downloading the databases.

#### Observed
```
(diamond) rpetit@staphopia:/data$ rfplasmid
Warning: Jellyfish is not installed. Not recommended
Error: /local/home/rpetit/miniconda3/envs/diamond/lib/python3.9/site-packages/RFPlasmid/plasmiddb_cge.dmnd does not exist.
Downloading plasmid databases.. Be patient. You may have to run this script with sudo
This script needs wget and diamond
Downloading databases from http://klif.uu.nl/download/plasmid_db/
Please be patient. This is a large download

... truncated ...
```

#### Expected
```
(diamond) rpetit@staphopia:~$ rfplasmid


Error; no arguments
usage: rfplasmid.py [-h] [--species SPECIES] [--input INPUT] [--training] [--specieslist] [--jelly] [--out OUT] [--debug] [--threads THREADS]

optional arguments:
  -h, --help         show this help message and exit
  --species SPECIES  define species
  --input INPUT      directory with input fasta files
  --training         trainings mode Random Forest
  --specieslist      list of species
  --jelly            run jellyfish as kmer-count (faster)
  --out OUT          specify output directory
  --debug            no cleanup of intermediate files
  --threads THREADS  specify number of threads to be used, default is max available threads up to 16 threads
```

**Comment by aldertzomer** [comment]
rfplasmid is a helper script for the pip package, it does not need to be included.

**Comment by rpetit3** [comment]
I like the helper script a lot because it checks for dependencies and auto downloads the database for you.

For conda I can include both `rfplasmid` (actually running RFPlasmid) and `rfplasmid.py` (just testing purposes) but I wonder if it might confuse users.

Do you think it would be useful to add a check in the helper script, that if `--version` or `--help` is used, skip the database download? Something like this:

```
#!/bin/bash
rfplasmidpath=`python3 -c "import RFPlasmid as _; print(_.__path__)"|sed 's/^\[.//' |sed 's/.\]$//'`

# Check for help/version/empty
SKIP_CHECKS=0
if [[ $# == 0 ]]; then
  SKIP_CHECKS=1
else
  while [[ $# -gt 0 ]]; do
    arg="$1"
    case $arg in
        -h|--help|--version)
          SKIP_CHECKS=1
          shift 
          ;;
        *)
          shift 
          ;;
    esac
  done
fi

if [[ "${SKIP_CHECKS}" -eq 0 ]]; then
  if ! [ -x "$(command -v diamond)" ]; then
    echo 'Error: diamond is not installed.' >&2
    exit 1
  fi

  if ! [ -x "$(command -v checkm)" ]; then
    echo 'Error: checkm is not installed.' >&2
    exit 1
  fi

  if ! [ -x "$(command -v R)" ]; then
    echo 'Error: R is not installed.' >&2
    exit 1
  fi

  if ! [ -x "$(command -v python3)" ]; then
    echo 'Error: python3 is not installed.' >&2
    exit 1
  fi

  if ! [ -x "$(command -v jellyfish)" ]; then
    echo 'Warning: Jellyfish is not installed. Not recommended' >&2
  fi

  FILE="$rfplasmidpath"/plasmiddb_cge.dmnd
  if [ -f "$FILE" ]; then
      echo
  else
      echo "Error: $FILE does not exist."
      echo "Downloading plasmid databases.. Be patient. You may have to run this script with sudo"
      cd "$rfplasmidpath"
      bash ./getdb.sh
      echo "$FILE installed. Please try rfplasmid again"
      exit 1
  fi

  FILE2="$rfplasmidpath"/plasmiddb_total.dmnd
  if [ -f "$FILE2" ]; then
      echo
  else
      echo "Error: $FILE2 does not exist."
      echo "Downloading plasmid databases.. Be patient. You may have to run this script with sudo"
      cd "$rfplasmidpath"
      bash ./getdb.sh
      echo "$FILE2 installed. Please try rfplasmid again"
      exit 1
  fi
fi

python3 "$rfplasmidpath"/rfplasmid.py $@
```

**Comment by aldertzomer** [comment]
We have included an initialize function. it only downloads databases when you ask for it. Linda is updating the pip package right now

**Comment by rpetit3** [comment]
Sounds good, I'll add a post install message that says "run this to download database" Something similar to [this](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/phigaro/post-link.sh)

**Comment by aldertzomer** [comment]
Thank you !  The user has to run "rfplasmid initialize".  We have included your name in the acknowledgments section of the paper, I hope you are ok with that.

**Comment by rpetit3** [comment]
Totally ok with that, thank you very much! Happy to help out. 

I think once the next version is available on pip, I should be all set for a Conda recipe.

**Comment by rpetit3** [comment]
I think we are close, the helper script still requires downloading the database to run `--help` or `--version`.

```
rfplasmid --help
Warning: Jellyfish is not installed. Not recommended
Error: /local/home/rpetit/miniconda3/envs/rfplasmid/lib/python3.7/site-packages/RFPlasmid/plasmiddb_cge.dmnd does not exist. Run rfplasmid initialize to download databases
```

Is that the expected behavior? If so, that's ok, but I will have to add `rfplasmid.py` to the PATH as well for the conda tests section.
```
rfplasmid --help  # requires db
rfplasmid --version  # requires db

rfplasmid.py --help # passes
rfplasmid.py --version # passes
```

**Comment by aldertzomer** [comment]
adding rfplasmid.py to the path would be ideal. the helper script is only there because sometimes pip places your package at some unusual place and then running it is difficult, as pip does not add stuff to your path. I will ask Linda to add the --help/--version bit

**Comment by rpetit3** [comment]
I think I'm all set on the Conda recipe. I'll get started on it!  Thank you very much of all the help (You too @LindavdGvB!)

Going to go ahead and close this one.

**Comment by aldertzomer** [comment]
Hi Robert, one more moment, we have made a few cosmetic changes to the helper script. it does now what you describe above to fix all issues.

**Comment by rpetit3** [comment]
Oh that's exciting! I'll block the Bioconda recipe until you're all set.
