### ISSUE TITLE
tar.gz for PyPi release?

### ISSUE THREAD

**Issue by rpetit3** [aldertzomer/RFPlasmid#14]
Hello! 

Been thinking about the Bioconda release. I'm not familiar with PyPi releases, currently there is only a whl for the release. Is it possible to also get a tar.gz from PyPi.

I think the *.tar.gz will work better with the Bioconda auto updater.

Thanks!

**Comment by aldertzomer** [comment]
The tar.gz may not place all files correctly in the right folder, the helper script may be an issue.

**Comment by rpetit3** [comment]
Sounds good, I'll close this.
