### ISSUE TITLE
Advice for reconstructing plasmids

### ISSUE THREAD

**Issue by iaposto** [aldertzomer/RFPlasmid#15]
Congrats for your work! I would be grateful for any advice on how to use the output of RFPlasmid to reconstruct the different plasmids that might be present in an assembly by e.g. attempting to bin predicted plasmid contigs into discrete units. I was also wondering if you have any plans to integrate such an approach in your tool.

Thanks!

**Comment by aldertzomer** [comment]
I think this tool might help: https://academic.oup.com/bioinformatics/article/36/12/3874/5818483 . The output of rfplasmid can be used as input for gplas if I'm not mistaken (you need to make a few changes).

**Comment by iaposto** [comment]
I tried gplas before using some closed E. coli genomes of our lab for benchmarking but results were not satisfactory (mixed plasmids in same bin, at least for my dataset). The input for gplas is gfa (assembly graphs) but I will check if it's possible to tweak it in order to accept fasta and try it.

**Comment by aldertzomer** [comment]
You can ask Anita Schurch, i believe she was working on making it
compatible.


Op do 18 mrt. 2021 17:54 schreef feanor1914 ***@***.***>:

**Comment by iaposto** [comment]
Will do, thanks.
