### ISSUE TITLE
species list and models

### ISSUE THREAD

**Issue by JPegorino** [aldertzomer/RFPlasmid#16]
I notice that the specieslist.txt includes some genera with no corresponding .rfo file. 
To run rfplasmid for one of these genera, can I use the species model or would I need to use the "Bacteria" model?
Thanks!

**Comment by aldertzomer** [comment]
Hi! Can you tell me which one you need? We may have a model but it hasn't passed our quality criteria, but it may be useful to you. Alternatively the Bacteria model works well, but performance may be less for shorter contigs for which no genes can be detected.
