### ISSUE TITLE
Question on chromosome/plasmid votes 

### ISSUE THREAD

**Issue by biflorenzi** [aldertzomer/RFPlasmid#18]
Hello!
 
I am using this tool in my master thesis to explore the association between ESBLs and insertion sequences in Enterobacteriaceae. I am wondering if when interpreting the output of the tool I should introduce a filter to remove those instances in which the classification is less sure, e.g. only accept the classification to chromosome/plasmid of a contig if the vote is higher than 0.8. What is your view on this? I imagine it probably depends on what I am doing precisely but maybe you still have a take on the matter?

Thanks and kind regards,
Biancamaria

**Comment by aldertzomer** [comment]
Hi Biancamaria

We generally use a cutoff of 0.6, but it also depends on what the question is of course.
Best wishes
Aldert

**Comment by biflorenzi** [comment]
I see, thanks!

Kind regards,
Biancamaria
