### ISSUE TITLE
Error in merging of contig files

### ISSUE THREAD

**Issue by lisavader** [aldertzomer/RFPlasmid#19]
Hello!
I encountered the following issue:

Start merging contig files
Create df_files ; done
Traceback (most recent call last):
  File "/home/dla_mm/lvader/data/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/RFPlasmid/rfplasmid.py", line 337, in <module>
    df1a = pd.concat(dfList)
  File "/home/dla_mm/lvader/data/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 285, in concat
    op = _Concatenator(
  File "/home/dla_mm/lvader/data/miniconda3/envs/rfplasmid/lib/python3.9/site-packages/pandas/core/reshape/concat.py", line 342, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate

Does anyone know what this could be caused by? (The issue was found before, on https://github.com/aldertzomer/RFPlasmid/issues/5#issuecomment-684757309)
I'm using version 0.0.17, and downloaded RFPlasmid via conda.

Thanks!

**Comment by aldertzomer** [comment]
Do your have files have the extension .fasta and are they fasta files? As it generally does that when specific output files are missing.

**Comment by lisavader** [comment]
Yes, they are .fna files with generic SPAdes headers (eg. >DRR192221_202105251828_1_length_468813_cov_43.132528)

**Comment by aldertzomer** [comment]
Hi Lisa, did you call them .fna or .fasta ? as .fna does not get picked up..

**Comment by lisavader** [comment]
Ah that's the issue then, thanks!

**Comment by aldertzomer** [comment]
Let me know if it works. in the meantime I'll add recognizing .fna extension as a feature request.

**Comment by lisavader** [comment]
Thank you Aldert, it does work now after renaming the .fna files to .fasta. Good to see that .fna support will be added!
