### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('')?

### ISSUE THREAD

**Issue by abrozzi** [aldertzomer/RFPlasmid#24]
Dear,

got this error when trying to install checkM:

```
(rfplasmid) abrozzi@alessandrosiMac .checkm % checkm data setRoot /Users/abrozzi/.checkm 
  File "/Users/abrozzi/miniconda/envs/rfplasmid/bin/checkm", line 58
    print ''
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('')?
```

I've followed step by step the instructions.

Any hint to solve it?

All the bests,
Alex

**Comment by aldertzomer** [comment]
Hi Alex
I'm not sure, is this python2 or python3? As that is a common error with a python2 program being run with python3. The only think I can think of is that you installed the older version of checkm which was still python2 but are trying to run it using python3.

**Comment by abrozzi** [comment]
Thank you!

I followed this:

```
conda create -n rfplasmid -c conda-forge -c bioconda rfplasmid ; conda activate rfplasmid
```

```
$  mkdir .checkm
$  cd .checkm
$  wget https://data.ace.uq.edu.au/public/CheckM_databases/checkm_data_2015_01_16.tar.gz
$  tar xzvf checkm_data_2015_01_16.tar.gz
$  checkm data setRoot ~/.checkm
```

```
(rfplasmid) abrozzi@alessandrosiMac .checkm % which checkm
/Users/abrozzi/miniconda/envs/rfplasmid/bin/checkm
```

**Comment by aldertzomer** [comment]
can you do 
head -n 1 `which checkm`

**Comment by aldertzomer** [comment]
mmm with `

**Comment by abrozzi** [comment]
Here we go:

```
(rfplasmid) abrozzi@alessandrosiMac .checkm % head -n1 `which checkm`
#!/Users/abrozzi/miniconda/envs/rfplasmid/bin/python
```

```
(rfplasmid) abrozzi@alessandrosiMac .checkm % /Users/abrozzi/miniconda/envs/rfplasmid/bin/python
Python 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 18:49:43) 
[GCC Clang 11.1.0] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by aldertzomer** [comment]
That is definitely a python2 version. the python3 version has  print ('') at line 58 and the python2 version has print"" , which does not work in python3. There is a reference to this in the checkm bugtracker: https://github.com/Ecogenomics/CheckM/issues/178 but that is closed.

**Comment by aldertzomer** [comment]
The only thing I can imagine is that it comes from a different conda repository, e.g. https://anaconda.org/mittaldeepti/checkm-genome , that is a version lower than 1.1.x and is python2. The bioconda one is 1.1.3

**Comment by abrozzi** [comment]
Hi,
thank you very much for your support.
I tried this:

```
conda create -n checkm python=3.9
conda activate checkm
conda install numpy matplotlib pysam
conda install hmmer prodigal pplacer
pip3 install checkm-genome
```

and 

```
conda activate checkm
checkm data setRoot ~/.checkm
```

worked properly.

But when I run ```rfplasmid``` gives the same error. :(

-A

**Comment by aldertzomer** [comment]
did you install rfplasmid inside your checkm conda env or in a separate one? as the checkm in your rfplasmid env may be the wrong one
