### ISSUE TITLE
Missing prediction file

### ISSUE THREAD

**Issue by zhichusun** [aldertzomer/RFPlasmid#26]
> #classifying
> Args <- commandArgs(TRUE)
> library(randomForest)
randomForest 4.6-14
Type rfNews() to see new features/changes/bug fixes.
> model<-paste(Args[2],"/",Args[1],".rfo",sep="")
> load(model)
> df<-read.table("outputdataframe.csv", sep=",", header=T, row.names=1)
Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 68 did not have 1034 elements
Calls: read.table -> scan
Execution halted
Prediction done
When I run more than 400 genomes, I can't generate the prediction file at the end, only the outdateframe.csv file, what's going on?

**Comment by aldertzomer** [comment]
checkm has an issue with very large datasets, although normally that is an issue with ~1000 genomes or so. I think you need to analyze it per 200 maybe?
