### ISSUE TITLE
Error: file is too short for prediction

### ISSUE THREAD

**Issue by cchauve** [aldertzomer/RFPlasmid#28]
I am trying to run RFPlasmid on FASTA files containing some very short contigs (as small as 1 base).
for aFASTA file `XXX.fasta` I get the following error message
```
Start RFPlasmid, version 0.0.18
copy original contig names
cleanup contig names
start Checkm
Error: File XXX is too short for prediction
```

Any help would be welcome.

Thank you

cedric chauve

**Comment by aldertzomer** [comment]
I guess the solution would be to use larger contigs. 1 bp is awfully short.
Below 1 kb the prediction is not great anyway.



Op do 4 aug. 2022 17:56 schreef Computational Methods for Comparative
Genomics at Simon Fraser University ***@***.***>:

**Comment by cchauve** [comment]
The same problem occurs when I filter all contigs of length below 10kb.

cedric chauve

**Comment by aldertzomer** [comment]
hi Cedric
Can you share the file that gives problems? 
thanks
Aldert

**Comment by cchauve** [comment]
Hello
Attached is a file that resulted in what I describe.
It contains very short contigs, but even after filtering them out to keep only contigs of lngth 100bp and above, RFPlasmid failed on it.
I had no problem with the online version of RFPlasmid, that could handle all my files.
cedric chauve
[efae-E4457.fasta.gz](https://github.com/aldertzomer/RFPlasmid/files/9352665/efae-E4457.fasta.gz)

**Comment by aldertzomer** [comment]
it runs just fine (?). Do you run it straight on the .gz file or on the .fasta file? 

"","prediction","votes chromosomal","votes plasmid","contigID"
"efae-E4457_1","c",0.636,0.364,"1 length=153919 depth=0.84x"
"efae-E4457_10","p",0.477,0.523,"10 length=80749 depth=1.09x"
"efae-E4457_100","p",0.366,0.634,"100 length=1814 depth=22.92x"
"efae-E4457_101","p",0.434,0.566,"101 length=1811 depth=15.97x"
"efae-E4457_102","p",0.44,0.56,"102 length=1683 depth=1.02x"
"efae-E4457_103","p",0.347,0.653,"103 length=1561 depth=32.43x"
"efae-E4457_104","c",0.705,0.295,"104 length=1537 depth=7.23x"
"efae-E4457_105","p",0.5,0.5,"105 length=1514 depth=7.24x"
"efae-E4457_106","p",0.371,0.629,"106 length=1513 depth=0.94x"
"efae-E4457_107","p",0.486,0.514,"107 length=1466 depth=3.58x"
"efae-E4457_108","c",0.708,0.292,"108 length=1397 depth=7.78x"
"efae-E4457_109","c",0.702,0.298,"109 length=1387 depth=7.26x"
"efae-E4457_11","c",0.644,0.356,"11 length=75867 depth=0.96x"
"efae-E4457_110","p",0.452,0.548,"110 length=1370 depth=1.94x"
"efae-E4457_111","p",0.421,0.579,"111 length=1364 depth=0.77x"
"efae-E4457_112","c",0.578,0.422,"112 length=1358 depth=0.42x"
"efae-E4457_113","p",0.441,0.559,"113 length=1336 depth=3.57x"
"efae-E4457_114","p",0.474,0.526,"114 length=1324 depth=14.42x"
"efae-E4457_115","c",0.55,0.45,"115 length=1323 depth=0.57x"
"efae-E4457_116","p",0.477,0.523,"116 length=1307 depth=1.12x"
"efae-E4457_117","p",0.477,0.523,"117 length=1306 depth=1.34x"
"efae-E4457_118","p",0.433,0.567,"118 length=1268 depth=0.93x"
"efae-E4457_119","p",0.436,0.564,"119 length=1182 depth=55.41x"
"efae-E4457_12","c",0.645,0.355,"12 length=70801 depth=0.80x"
"efae-E4457_120","c",0.507,0.493,"120 length=1177 depth=1.08x"
"efae-E4457_121","p",0.384,0.616,"121 length=1099 depth=3.05x"
"efae-E4457_122","c",0.506,0.494,"122 length=1098 depth=0.97x"
"efae-E4457_123","c",0.512,0.488,"123 length=1070 depth=1.89x"
"efae-E4457_124","p",0.479,0.521,"124 length=1065 depth=2.46x"
"efae-E4457_125","p",0.437,0.563,"125 length=1064 depth=3.02x"
"efae-E4457_126","p",0.486,0.514,"126 length=1047 depth=0.98x"
"efae-E4457_127","c",0.52,0.48,"127 length=1032 depth=2.63x"
"efae-E4457_128","c",0.555,0.445,"128 length=1029 depth=0.26x"
"efae-E4457_129","p",0.477,0.523,"129 length=1007 depth=5.34x"
"efae-E4457_13","p",0.474,0.526,"13 length=70710 depth=0.99x"
"efae-E4457_130","p",0.491,0.509,"130 length=979 depth=0.83x"
"efae-E4457_131","p",0.486,0.514,"131 length=947 depth=4.23x"
"efae-E4457_132","p",0.48,0.52,"132 length=866 depth=0.93x"
"efae-E4457_133","p",0.475,0.525,"133 length=866 depth=1.18x"
"efae-E4457_134","p",0.491,0.509,"134 length=795 depth=1.24x"
"efae-E4457_135","c",0.522,0.478,"135 length=795 depth=1.33x"
"efae-E4457_136","p",0.46,0.54,"136 length=795 depth=6.23x"
"efae-E4457_137","c",0.509,0.491,"137 length=780 depth=7.20x"
"efae-E4457_138","c",0.605,0.395,"138 length=777 depth=1.03x"
"efae-E4457_139","p",0.496,0.504,"139 length=723 depth=2.63x"
"efae-E4457_14","c",0.611,0.389,"14 length=67751 depth=0.78x"
"efae-E4457_140","c",0.51,0.49,"140 length=716 depth=8.96x"
"efae-E4457_141","p",0.459,0.541,"141 length=706 depth=6.05x"
"efae-E4457_142","c",0.511,0.489,"142 length=625 depth=16.95x"
"efae-E4457_143","c",0.562,0.438,"143 length=618 depth=1.27x"
"efae-E4457_144","c",0.569,0.431,"144 length=618 depth=1.65x"
"efae-E4457_145","c",0.628,0.372,"145 length=611 depth=2.02x"
"efae-E4457_146","c",0.533,0.467,"146 length=596 depth=2.69x"
"efae-E4457_147","c",0.532,0.468,"147 length=577 depth=2.22x"
"efae-E4457_148","c",0.602,0.398,"148 length=576 depth=8.63x"
"efae-E4457_149","p",0.49,0.51,"149 length=529 depth=2.22x"
"efae-E4457_15","c",0.638,0.362,"15 length=66349 depth=1.02x"
"efae-E4457_150","c",0.548,0.452,"150 length=481 depth=6.68x"
"efae-E4457_151","p",0.456,0.544,"151 length=480 depth=0.59x"
"efae-E4457_152","p",0.498,0.502,"152 length=468 depth=34.58x"
"efae-E4457_153","c",0.623,0.377,"153 length=462 depth=0.94x"
"efae-E4457_154","c",0.513,0.487,"154 length=460 depth=1.42x"
"efae-E4457_155","c",0.53,0.47,"155 length=460 depth=1.42x"
"efae-E4457_156","c",0.563,0.437,"156 length=459 depth=0.55x"
"efae-E4457_157","p",0.472,0.528,"157 length=437 depth=15.41x"
"efae-E4457_158","c",0.565,0.435,"158 length=436 depth=0.81x"
"efae-E4457_159","c",0.673,0.327,"159 length=434 depth=1.24x"
"efae-E4457_16","c",0.643,0.357,"16 length=60607 depth=0.88x"
"efae-E4457_160","c",0.656,0.344,"160 length=434 depth=1.37x"
"efae-E4457_161","c",0.572,0.428,"161 length=415 depth=2.35x"
"efae-E4457_162","c",0.638,0.362,"162 length=383 depth=0.85x"
"efae-E4457_163","c",0.595,0.405,"163 length=382 depth=1.29x"
"efae-E4457_164","c",0.619,0.381,"164 length=379 depth=1.45x"
"efae-E4457_165","p",0.465,0.535,"165 length=372 depth=0.61x"
"efae-E4457_166","c",0.535,0.465,"166 length=361 depth=1.75x"
"efae-E4457_167","c",0.56,0.44,"167 length=343 depth=2.27x"
"efae-E4457_168","c",0.546,0.454,"168 length=337 depth=15.55x"
"efae-E4457_169","c",0.553,0.447,"169 length=329 depth=2.07x"
"efae-E4457_17","p",0.474,0.526,"17 length=58669 depth=0.94x"
"efae-E4457_170","c",0.594,0.406,"170 length=326 depth=8.61x"
"efae-E4457_171","c",0.592,0.408,"171 length=324 depth=1.62x"
"efae-E4457_172","c",0.605,0.395,"172 length=315 depth=3.22x"
"efae-E4457_173","c",0.552,0.448,"173 length=313 depth=1.97x"
"efae-E4457_174","c",0.564,0.436,"174 length=313 depth=1.56x"
"efae-E4457_175","c",0.592,0.408,"175 length=304 depth=1.68x"
"efae-E4457_176","c",0.564,0.436,"176 length=304 depth=1.96x"
"efae-E4457_177","c",0.595,0.405,"177 length=300 depth=1.08x"
"efae-E4457_178","c",0.647,0.353,"178 length=286 depth=7.94x"
"efae-E4457_179","c",0.572,0.428,"179 length=284 depth=2.06x"
"efae-E4457_18","c",0.617,0.383,"18 length=58625 depth=0.90x"
"efae-E4457_180","c",0.606,0.394,"180 length=282 depth=1.86x"
"efae-E4457_181","c",0.615,0.385,"181 length=282 depth=1.67x"
"efae-E4457_182","c",0.584,0.416,"182 length=276 depth=2.32x"
"efae-E4457_183","c",0.646,0.354,"183 length=276 depth=1.36x"
"efae-E4457_184","c",0.524,0.476,"184 length=274 depth=2.26x"
"efae-E4457_185","c",0.569,0.431,"185 length=269 depth=2.73x"
"efae-E4457_186","c",0.575,0.425,"186 length=266 depth=1.61x"
"efae-E4457_187","c",0.532,0.468,"187 length=264 depth=2.15x"
"efae-E4457_188","c",0.557,0.443,"188 length=254 depth=7.17x"
"efae-E4457_189","c",0.546,0.454,"189 length=253 depth=1.22x"
"efae-E4457_19","c",0.629,0.371,"19 length=56444 depth=1.00x"
"efae-E4457_190","c",0.569,0.431,"190 length=248 depth=21.97x"
"efae-E4457_191","c",0.546,0.454,"191 length=241 depth=1.66x"
"efae-E4457_192","c",0.551,0.449,"192 length=239 depth=1.04x"
"efae-E4457_193","c",0.608,0.392,"193 length=235 depth=1.02x"
"efae-E4457_194","c",0.567,0.433,"194 length=230 depth=3.80x"
"efae-E4457_195","c",0.585,0.415,"195 length=227 depth=9.58x"
"efae-E4457_196","c",0.588,0.412,"196 length=224 depth=2.34x"
"efae-E4457_197","c",0.604,0.396,"197 length=218 depth=2.63x"
"efae-E4457_198","c",0.57,0.43,"198 length=217 depth=10.56x"
"efae-E4457_199","c",0.57,0.43,"199 length=206 depth=1.68x"
"efae-E4457_2","p",0.459,0.541,"2 length=132337 depth=0.90x"
"efae-E4457_20","c",0.643,0.357,"20 length=55665 depth=1.01x"
"efae-E4457_200","c",0.599,0.401,"200 length=206 depth=1.10x"
"efae-E4457_201","c",0.627,0.373,"201 length=204 depth=11.77x"
"efae-E4457_202","c",0.603,0.397,"202 length=203 depth=1.66x"
"efae-E4457_203","c",0.621,0.379,"203 length=203 depth=1.16x"
"efae-E4457_204","c",0.631,0.369,"204 length=202 depth=0.81x"
"efae-E4457_205","c",0.576,0.424,"205 length=201 depth=0.91x"
"efae-E4457_206","c",0.623,0.377,"206 length=196 depth=4.09x"
"efae-E4457_207","c",0.605,0.395,"207 length=194 depth=1.53x"
"efae-E4457_208","c",0.609,0.391,"208 length=193 depth=0.79x"
"efae-E4457_209","c",0.615,0.385,"209 length=193 depth=0.72x"
"efae-E4457_21","c",0.525,0.475,"21 length=55662 depth=1.03x"
"efae-E4457_210","c",0.618,0.382,"210 length=193 depth=7.30x"
"efae-E4457_211","c",0.551,0.449,"211 length=182 depth=1.65x"
"efae-E4457_212","c",0.611,0.389,"212 length=182 depth=4.09x"
"efae-E4457_213","c",0.623,0.377,"213 length=180 depth=1.05x"
"efae-E4457_214","c",0.594,0.406,"214 length=180 depth=1.94x"
"efae-E4457_215","c",0.63,0.37,"215 length=179 depth=3.26x"
"efae-E4457_216","c",0.615,0.385,"216 length=171 depth=1.16x"
"efae-E4457_217","c",0.614,0.386,"217 length=167 depth=1.13x"
"efae-E4457_218","c",0.523,0.477,"218 length=161 depth=0.90x"
"efae-E4457_219","c",0.597,0.403,"219 length=160 depth=87.31x"
"efae-E4457_22","p",0.186,0.814,"22 length=53390 depth=0.81x"
"efae-E4457_220","c",0.633,0.367,"220 length=159 depth=1.23x"
"efae-E4457_221","c",0.583,0.417,"221 length=157 depth=5.08x"
"efae-E4457_222","c",0.594,0.406,"222 length=156 depth=34.05x"
"efae-E4457_223","c",0.594,0.406,"223 length=151 depth=2.37x"
"efae-E4457_224","c",0.552,0.448,"224 length=149 depth=1.54x"
"efae-E4457_225","c",0.607,0.393,"225 length=147 depth=1.84x"
"efae-E4457_226","c",0.59,0.41,"226 length=147 depth=2.02x"
"efae-E4457_227","c",0.602,0.398,"227 length=147 depth=2.57x"
"efae-E4457_228","c",0.597,0.403,"228 length=145 depth=2.65x"
"efae-E4457_229","c",0.614,0.386,"229 length=145 depth=3.84x"
"efae-E4457_23","c",0.504,0.496,"23 length=52981 depth=0.95x"
"efae-E4457_230","c",0.591,0.409,"230 length=144 depth=51.66x"
"efae-E4457_231","c",0.557,0.443,"231 length=143 depth=1.04x"
"efae-E4457_232","c",0.602,0.398,"232 length=142 depth=4.03x"
"efae-E4457_233","c",0.591,0.409,"233 length=136 depth=5.15x"
"efae-E4457_234","c",0.59,0.41,"234 length=130 depth=24.14x"
"efae-E4457_235","c",0.594,0.406,"235 length=128 depth=3.35x"
"efae-E4457_236","c",0.58,0.42,"236 length=124 depth=1.23x"
"efae-E4457_237","c",0.574,0.426,"237 length=123 depth=2.07x"
"efae-E4457_238","c",0.578,0.422,"238 length=122 depth=38.81x"
"efae-E4457_239","c",0.623,0.377,"239 length=120 depth=60.63x"
"efae-E4457_24","p",0.493,0.507,"24 length=47880 depth=0.96x"
"efae-E4457_240","c",0.595,0.405,"240 length=119 depth=1.07x"
"efae-E4457_241","c",0.568,0.432,"241 length=114 depth=79.22x"
"efae-E4457_242","c",0.552,0.448,"242 length=108 depth=1.65x"
"efae-E4457_243","c",0.579,0.421,"243 length=105 depth=6.50x"
"efae-E4457_244","c",0.567,0.433,"244 length=102 depth=1.66x"
"efae-E4457_245","c",0.53,0.47,"245 length=102 depth=9.46x"
"efae-E4457_25","p",0.206,0.794,"25 length=42617 depth=0.91x"
"efae-E4457_26","p",0.496,0.504,"26 length=37633 depth=0.85x"
"efae-E4457_27","c",0.664,0.336,"27 length=33297 depth=0.80x"
"efae-E4457_28","c",0.652,0.348,"28 length=32539 depth=0.96x"
"efae-E4457_29","c",0.584,0.416,"29 length=32141 depth=0.85x"
"efae-E4457_3","p",0.456,0.544,"3 length=101866 depth=1.00x"
"efae-E4457_30","c",0.534,0.466,"30 length=29693 depth=0.86x"
"efae-E4457_31","c",0.62,0.38,"31 length=29598 depth=0.94x"
"efae-E4457_32","c",0.667,0.333,"32 length=26890 depth=0.95x"
"efae-E4457_33","c",0.652,0.348,"33 length=23834 depth=1.03x"
"efae-E4457_34","c",0.579,0.421,"34 length=23103 depth=0.75x"
"efae-E4457_35","c",0.615,0.385,"35 length=21903 depth=0.89x"
"efae-E4457_36","p",0.166,0.834,"36 length=21655 depth=1.60x"
"efae-E4457_37","p",0.142,0.858,"37 length=21139 depth=1.00x"
"efae-E4457_38","c",0.644,0.356,"38 length=20668 depth=0.86x"
"efae-E4457_39","c",0.627,0.373,"39 length=20512 depth=0.84x"
"efae-E4457_4","c",0.511,0.489,"4 length=99255 depth=1.06x"
"efae-E4457_40","c",0.645,0.355,"40 length=20271 depth=0.99x"
"efae-E4457_41","c",0.636,0.364,"41 length=18877 depth=0.92x"
"efae-E4457_42","c",0.656,0.344,"42 length=18253 depth=1.03x"
"efae-E4457_43","p",0.321,0.679,"43 length=18225 depth=1.00x"
"efae-E4457_44","c",0.591,0.409,"44 length=17917 depth=0.89x"
"efae-E4457_45","c",0.655,0.345,"45 length=15497 depth=0.96x"
"efae-E4457_46","c",0.626,0.374,"46 length=15250 depth=0.93x"
"efae-E4457_47","p",0.164,0.836,"47 length=14973 depth=1.29x"
"efae-E4457_48","p",0.407,0.593,"48 length=14943 depth=0.88x"
"efae-E4457_49","c",0.662,0.338,"49 length=14174 depth=1.06x"
"efae-E4457_5","p",0.445,0.555,"5 length=96262 depth=1.00x"
"efae-E4457_50","c",0.641,0.359,"50 length=13152 depth=1.09x"
"efae-E4457_51","p",0.432,0.568,"51 length=12514 depth=0.70x"
"efae-E4457_52","p",0.237,0.763,"52 length=12472 depth=1.22x"
"efae-E4457_53","p",0.486,0.514,"53 length=12088 depth=0.99x"
"efae-E4457_54","c",0.646,0.354,"54 length=11173 depth=1.03x"
"efae-E4457_55","p",0.209,0.791,"55 length=10194 depth=1.14x"
"efae-E4457_56","p",0.195,0.805,"56 length=10167 depth=1.08x"
"efae-E4457_57","c",0.648,0.352,"57 length=9949 depth=0.78x"
"efae-E4457_58","c",0.588,0.412,"58 length=9827 depth=0.72x"
"efae-E4457_59","p",0.192,0.808,"59 length=9720 depth=1.20x"
"efae-E4457_6","p",0.468,0.532,"6 length=91102 depth=1.02x"
"efae-E4457_60","p",0.127,0.873,"60 length=9317 depth=4.28x circular=true"
"efae-E4457_61","p",0.268,0.732,"61 length=9308 depth=0.77x"
"efae-E4457_62","c",0.587,0.413,"62 length=9215 depth=0.87x"
"efae-E4457_63","c",0.605,0.395,"63 length=9051 depth=0.78x"
"efae-E4457_64","c",0.605,0.395,"64 length=8936 depth=0.78x"
"efae-E4457_65","p",0.414,0.586,"65 length=8856 depth=0.87x"
"efae-E4457_66","p",0.26,0.74,"66 length=7908 depth=1.31x"
"efae-E4457_67","p",0.224,0.776,"67 length=7884 depth=1.43x"
"efae-E4457_68","c",0.616,0.384,"68 length=7284 depth=1.11x"
"efae-E4457_69","p",0.182,0.818,"69 length=6646 depth=0.80x"
"efae-E4457_7","c",0.628,0.372,"7 length=90492 depth=0.90x"
"efae-E4457_70","p",0.283,0.717,"70 length=6032 depth=1.16x"
"efae-E4457_71","p",0.209,0.791,"71 length=5429 depth=0.90x"
"efae-E4457_72","c",0.6,0.4,"72 length=5021 depth=0.94x"
"efae-E4457_73","p",0.226,0.774,"73 length=5014 depth=0.96x"
"efae-E4457_74","p",0.17,0.83,"74 length=4931 depth=0.79x"
"efae-E4457_75","p",0.202,0.798,"75 length=4692 depth=1.26x"
"efae-E4457_76","c",0.62,0.38,"76 length=4692 depth=0.87x"
"efae-E4457_77","c",0.544,0.456,"77 length=4577 depth=0.48x"
"efae-E4457_78","c",0.648,0.352,"78 length=4519 depth=0.85x"
"efae-E4457_79","p",0.271,0.729,"79 length=4514 depth=0.94x"
"efae-E4457_8","c",0.646,0.354,"8 length=86940 depth=1.07x"
"efae-E4457_80","p",0.252,0.748,"80 length=4408 depth=11.89x circular=true"
"efae-E4457_81","c",0.646,0.354,"81 length=4032 depth=1.03x"
"efae-E4457_82","p",0.337,0.663,"82 length=3938 depth=0.99x"
"efae-E4457_83","c",0.603,0.397,"83 length=3808 depth=0.38x"
"efae-E4457_84","p",0.314,0.686,"84 length=3762 depth=1.18x"
"efae-E4457_85","p",0.255,0.745,"85 length=3757 depth=0.84x"
"efae-E4457_86","p",0.234,0.766,"86 length=3718 depth=0.69x"
"efae-E4457_87","p",0.276,0.724,"87 length=3394 depth=1.70x"
"efae-E4457_88","c",0.607,0.393,"88 length=3025 depth=0.87x"
"efae-E4457_89","p",0.344,0.656,"89 length=2797 depth=13.91x"
"efae-E4457_9","c",0.669,0.331,"9 length=82565 depth=0.86x"
"efae-E4457_90","p",0.42,0.58,"90 length=2505 depth=1.13x"
"efae-E4457_91","c",0.617,0.383,"91 length=2408 depth=0.97x"
"efae-E4457_92","p",0.392,0.608,"92 length=2391 depth=39.09x"
"efae-E4457_93","p",0.277,0.723,"93 length=2316 depth=0.77x"
"efae-E4457_94","c",0.531,0.469,"94 length=2061 depth=0.54x"
"efae-E4457_95","p",0.449,0.551,"95 length=2046 depth=1.11x"
"efae-E4457_96","p",0.462,0.538,"96 length=1976 depth=14.66x"
"efae-E4457_97","c",0.592,0.408,"97 length=1973 depth=0.27x"
"efae-E4457_98","p",0.378,0.622,"98 length=1903 depth=0.79x"
"efae-E4457_99","p",0.349,0.651,"99 length=1893 depth=16.23x"

**Comment by cchauve** [comment]
Hello

It runs on the FASTA file. There must be an issue with my local installation then.

cedric chauve

**Comment by aldertzomer** [comment]
There is no functionality to gunzip files in rfplasmid. glad that it works.
