### ISSUE TITLE
error when running on specific fasta files

### ISSUE THREAD

**Issue by sapuizait** [aldertzomer/RFPlasmid#30]
First of all thank you for your wonderful software!
I ve been trying to run it on MAGs from metagenomes on a slurm server. Installation was done with conda and everything seems to be working fine. 
However, when running individually for certain MAG fasta files i get the error below.
Here is the funny part; if i run all MAGs in one go, it runs fine (even though I only get the prediction table and i cannot get the checkm output - dont know if thats normal)
I attach two files one that the software is running it wo errors (4_83) and one that gives the error below (3_16). Funnily enough, the 4_83 (which runs fine) does not appear to have any plasmid regions (all predictions are chromosomal) but the 3_16 does...
fasta files can be downloaded here: https://filebin.net/wiu19addr2va9338
Any ideas?

Start kmer count
You have selected kmer-counting with jellyfish
Jellyfish kmer-count done
Count contig length
count contig length ; done
Start merging contig files
Create df_files ; done
Start to add blast output to dataframe
/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/RFPlasmid/rfplasmid.py:370: FutureWarning: In a future version of pandas all arguments of StringMethods.rsplit except for the argument 'pat' will be keyword-only.
  df4['genome'], df4['contig'] = df4['source'].str.rsplit('_', 1).str
/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/RFPlasmid/rfplasmid.py:370: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  df4['genome'], df4['contig'] = df4['source'].str.rsplit('_', 1).str
/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/RFPlasmid/rfplasmid.py:388: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df5a['source'] = df5a.genome.astype(str).str.cat(df5a.contig.astype(str), sep='_')
/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/RFPlasmid/rfplasmid.py:402: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df5b['kmer_number'] = df5b.contig_length - 4
Traceback (most recent call last):
  File "/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3800, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'SCM'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/RFPlasmid/rfplasmid.py", line 406, in <module>
    df5b['SCM_genes'] = df5b['SCM']/df5b['genes']
  File "/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/pandas/core/frame.py", line 3805, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/pasapoun/miniconda3/envs/rfplasmid/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3802, in get_loc
    raise KeyError(key) from err
KeyError: 'SCM'

**Comment by aldertzomer** [comment]
none but it may have to with issue #32. closing for now, but please reopen if it happens again. We are currently fixing issue #32
