### ISSUE TITLE
conda installed RFPlasmid --specieslist get "variable not defined" error

### ISSUE THREAD

**Issue by luan3665** [aldertzomer/RFPlasmid#31]
Hi, I was using this tool and try to check the flag --specieslist, but get this error from python: "NameError: name 'df_species' is not defined"

Locally, I just rise up the 4 lines close to df_species definition before the args.specieslist check and it works fine. Just in case you wanna update the code submitted on conda rep ;)

the script in question were "~/miniconda3/envs/plasmidfinder/lib/python3.7/site-packages/RFPlasmid/rfplasmid.py"

**Comment by LindavdGvB** [comment]
Thanks, we have fixed it.
