### ISSUE TITLE
getdb.sh failed: connection refused 

### ISSUE THREAD

**Issue by kuheng3** [aldertzomer/RFPlasmid#33]
Hi Dr. A.L. (Aldert) Zomer,

I have been trying to download the plasmid database using either the getdb.sh command or "rfplasmid --initialize", but I keep receiving a "connection refused" error. Is there another way I can obtain the plasmid databases (plasmiddb_total.dmnd and plasmiddb_cge.dmnd)?

Thank you in advance for your help.

**Comment by aldertzomer** [comment]
the server was down, is fixed now.
