### ISSUE TITLE
when i use  conda install -c bioconda rfplasmid to install the software, some errors happen

### ISSUE THREAD

**Issue by a-piece-of-teemo** [aldertzomer/RFPlasmid#34]
when i use  conda install -c bioconda rfplasmid to install the software, some errors happen
![image](https://github.com/aldertzomer/RFPlasmid/assets/113283540/515cd5c1-3e28-4339-bdb8-54e259d500d4)
I wonder how to solve this problem？

**Comment by aldertzomer** [comment]
For some reason your computer resolves Zenodo incorrectly and you fail to download the checkm database. This is an issue that your network has with the checkm installation. Both we cannot solve. You probably have to talk to your network admin why zenodo.org resolves to 0.0.0.0 and not to the actual ip address. I assume it’s firewalled/blocked by your network.
