### ISSUE TITLE
Plans for Bioconda?

### ISSUE THREAD

**Issue by rpetit3** [aldertzomer/RFPlasmid#6]
Hello!

Really looking forward to giving RFPlasmid a go. Quick question, do you plan on submitting a recipe for Bioconda? If not, do you mind if I go ahead and make one for you?

Thank you!
Robert

**Comment by aldertzomer** [comment]
Hi Robert
We have it in pip , we're not really experts on conda, we mostly use pip or source based install, but if you want to do so, please go ahead. What do you need from us to make it easier for you?
best wishes
Aldert

**Comment by rpetit3** [comment]
Is there a way to specify the location for DIAMOND databases (`plasmiddb_total` and `plasmiddb_cge`) or is it assumed in the launch directory?

**Comment by aldertzomer** [comment]
It is assumed to be in the launch directory

**Comment by rpetit3** [comment]
I think I'm about there on starting to create a bioconda recipe.

A very minor thing, Biopython isn't listed as a dependency. After installing everything then running rfplasmid.py:

```
python3 /local/home/rpetit/miniconda3/envs/rfplasmid/lib/python3.7/site-packages/RFPlasmid/rfplasmid.py --help
Traceback (most recent call last):
  File "/local/home/rpetit/miniconda3/envs/rfplasmid/lib/python3.7/site-packages/RFPlasmid/rfplasmid.py", line 6, in <module>
    from Bio import SeqIO
ModuleNotFoundError: No module named 'Bio'
```

**Comment by rpetit3** [comment]
I submitted a PR to add RFPlasmid to Biocconda (https://github.com/bioconda/bioconda-recipes/pull/25849)

If you don't mind, could you double [check the dependencies](https://github.com/bioconda/bioconda-recipes/pull/25849/files#diff-86c11b99cf39d117abeefbc8603e0463c613e8e67862229c899f13b8eeda89d2R23-R31) I have listed? Just want to make sure I didn't miss anything. Thanks!

**Comment by aldertzomer** [comment]
It is complete now, version 0.015 on pip and here on github are identical. The pip packages installs a bash helper script as well. The dependencies are in order.  rfplasmid imports the following python libs, which should be available. 

import os, sys, glob, argparse, shutil, multiprocessing
import pandas as pd
import numpy as np
from Bio import SeqIO
from collections import defaultdict
from itertools import groupby
from datetime import datetime
from contextlib import suppress

**Comment by rpetit3** [comment]
Good news! RFPlasmid is now available on Bioconda

```
conda create -n rfplasmid -c conda-forge -c bioconda rfplasmid
```

I'm going to go ahead and close this. 

@aldertzomer and @LindavdGvB thank you very much for all your help!

**Comment by aldertzomer** [comment]
Robert, thank you very much!
