### ISSUE TITLE
Ability to specify location of databases

### ISSUE THREAD

**Issue by rpetit3** [aldertzomer/RFPlasmid#8]
Hello!

I think it would be useful if the databases locations (`plasmiddb_total` and `plasmiddb_cge`) could be specified at runtime (e.g. `--db`). 

At the moment, I am either creating a symbolic link from a shared folder (`/databases/rfplasmid/`) or copying the database files between input directories each time I run RFPlasmid. 

#### Current
```
# current behavior
mkdir project_001
cd project_001
cp /databases/rfplasmid/* ./
python3 rfplasmid.py --species Campylobacter --input sample_001 --jelly --threads 8 --out sample_001
python3 rfplasmid.py --species Campylobacter --input sample_002 --jelly --threads 8 --out sample_002
python3 rfplasmid.py --species Campylobacter --input sample_003 --jelly --threads 8 --out sample_003

# some time later
mkdir project_002
cd project_002
cp /databases/rfplasmid/* ./
python3 rfplasmid.py --species Bacillus --input sample_101 --jelly --threads 8 --out sample_101 
python3 rfplasmid.py --species Bacillus --input sample_102 --jelly --threads 8 --out sample_101 
python3 rfplasmid.py --species Bacillus --input sample_103 --jelly --threads 8 --out sample_101 
```

#### Alternative
An alternative fould be to allow users to specify output directory for `getdb.sh`. Then users could use that path when running RFPlasmid.
```
bash getdb.sh ~/rfplasmid_db

mkdir project_001
cd project_001
python3 rfplasmid.py --species Campylobacter --input sample_001 --jelly --threads 8 --out sample_001 --db ~/rfplasmid/
python3 rfplasmid.py --species Campylobacter --input sample_002 --jelly --threads 8 --out sample_002 --db ~/rfplasmid/
python3 rfplasmid.py --species Campylobacter --input sample_003 --jelly --threads 8 --out sample_003 --db ~/rfplasmid/

# some time later
mkdir project_002
cd project_002
python3 rfplasmid.py --species Bacillus --input sample_101 --jelly --threads 8 --out sample_101 --db ~/rfplasmid/
python3 rfplasmid.py --species Bacillus --input sample_102 --jelly --threads 8 --out sample_101 --db ~/rfplasmid/
python3 rfplasmid.py --species Bacillus --input sample_103 --jelly --threads 8 --out sample_101 --db ~/rfplasmid/
```

The current behavior (find db in current directory) could be set to the the default value of `--db`.

Just an idea, but I think it would improve the usability of RFPlasmid.

Thank you!
Robert

**Comment by aldertzomer** [comment]
Why do you copy the entire package into your project dir?  You can just call it from everywhere. e.g.
python3 /some/folder/with/tools/RFPlasmid/rfplasmid.py --input /another/folder/with/data/genomes etc .

**Comment by rpetit3** [comment]
Ah. I see looking into it further (my mistake), the databases should be built where ever `rfplasmid.py` is located.

I guess I am little confused on `getdb.sh`, is it required post install?

**Comment by aldertzomer** [comment]
Unfortunately yes. One of the databases is too large for Github and also it needs to be rebuild because Diamond databases are not forward nor reverse compatible.

**Comment by rpetit3** [comment]
Haha just ignore me for now!

I just did pip install of rfplasmid and see that `getdb.sh` is automatic. 

```
rfplasmid --help
Warning: Jellyfish is not installed. Not recommended
Error: /local/home/rpetit/miniconda3/envs/diamond/lib/python3.9/site-packages/RFPlasmid/plasmiddb_cge.dmnd does not exist.
Downloading plasmid databases.. Be patient. You may have to run this script with sudo
```

Is there a way to run help without it downloading and setting up the databases? Asking for the conda install, at minimum we'd want to be able to `rfplasmid --help` for testing and downloading the DB will probably cause a time out.

**Comment by rpetit3** [comment]
Going to close this issue, since its not really an issue
