### ISSUE TITLE
--version to print version info

### ISSUE THREAD

**Issue by rpetit3** [aldertzomer/RFPlasmid#9]
I noticed you [print the version each run](https://github.com/aldertzomer/RFPlasmid/blob/master/rfplasmid.py#L68). I think it would be useful to have a `--version` option to pull version info.

Example
```
rpetit@server:~$ rfplasmid.py --version
rfplasmid 0.0.11
```

**Comment by aldertzomer** [comment]
I believe for traceability the version should be printed each run. Personally I believe every tool should do that. If in a years time one need to redo an analysis, the stderror log (if you capture that in your workflow) can be checked to see which version was used.  We can add another option though, it's just a few lines.

**Comment by rpetit3** [comment]
Totally agree with you on traceability.

For conda purposes having the `rfplasmid.py --version` will be useful for testing.

**Comment by rpetit3** [comment]
`--version` is available as of 0.0.12. Going to close, thank you!
